import ElegantBtn from '@/components/buttons/elegant-btn'
import SideBar from '@/components/side-bar/side-bar'
import {ModeToggle } from '@/components/mode-toggle'
import  { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import IntroPage from '@/components/intro-page/intro-page';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head/>
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <IntroPage />
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
      <div className='dark:text-white dark:bg-black text-black'>
        <ModeToggle />
          {children}
      </div>
      </ThemeProvider>
      <SideBar>
        <ElegantBtn />
        <ElegantBtn />
        <ElegantBtn />
        <ElegantBtn />
      </SideBar>
      </body>
    </html>
  );
}
